[package]
name = 'Todo'
version = '1.0.0'

[addresses]
Todo = "_"

[dependencies]
AptosFramework = {git = 'https://github.com/aptos-labs/aptos-core.git', subdir = 'aptos-move/framework/aptos-framework', rev = 'main'}